version: '3.8'

services:
  mongo:
    image: mongo:8.0.9
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  image-quarantine-bot:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: mongodb://mongo:27017/image-quarantine-bot
    depends_on:
      - mongo

volumes:
  mongo-data:
