version: '3.8'

services:
  mongo:
    image: mongo:8.0.9
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: local
      MONGO_INITDB_ROOT_PASSWORD: local

  image-quarantine-bot:
    build: .
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      MONGO_URI: mongodb://local:local@mongo:27017/image-quarantine-bot?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
